{% set name = "geospatial" %}
{% set version = "0.10.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/geospatial-{{ version }}.tar.gz
  sha256: 1f548f119c1dcbca6970bad54d67bcf408c1d6573f0fee0ba2ab01249afd47b3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - python >=3.8
    - bokeh
    - cartopy
    - cenpy
    - contextily
    - cubo
    - dask-geopandas
    - datashader
    - earthengine-api
    - earthpy
    - easystac
    - eemont
    - eomaps
    - eoreader
    - fiona
    - folium >=0.12.1
    - geemap >=0.24.0
    - geoalchemy2
    - geocube
    - geopandas >=0.10.2
    - geotiff
    - geosnap
    - geoviews
    - h3
    - h3-py
    - hvplot
    - ipygany
    - ipyleaflet >=0.16.0
    - ipyvtklink
    - keplergl
    - laspy
    - leafmap >=0.22.0
    - lidar
    - localtileserver >=0.6.1
    - mapboxgl
    - mapclassify
    - mapwidget
    - movingpandas
    - netcdf4
    - odc-stac
    - osmnx
    - owslib
    - panel
    - palettable
    - pillow
    - planetary-computer
    - plotly
    - proplot
    - psycopg2
    - pydeck
    - pygis >=0.6.0
    - pyntcloud
    - pysal
    - pyshp
    - pystac-client
    - python-mss
    - pyvista
    - radiant-mlhub
    - rasterio
    - rasterstats
    - rio-cogeo
    - rioxarray
    - s2cloudless
    - sarpy
    - satpy
    - sentinelsat
    - shapely
    - simplekml
    - sliderule
    - spyndex
    - sqlalchemy
    - stackstac
    - tropycal
    - usgs
    - whitebox
    - whiteboxgui
    - wxee
    - xarray
    - xarray_leaflet
    - xarray-spatial
    - xmovie
    - xyzservices

test:
  imports:
    - geospatial
  # commands:
  #   - pip check
  requires:
    - pip

about:
  home: https://github.com/giswqs/geospatial
  summary: A Python package for installing commonly used packages for geospatial analysis and data visualization with only one command.
  description: A Python package for installing commonly used packages for geospatial analysis and data visualization with only one command.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://geospatial.gishub.org
  dev_url: https://github.com/giswqs/geospatial

extra:
  recipe-maintainers:
    - giswqs
