{% set name = "geospatial" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/geospatial-{{ version }}.tar.gz
  sha256: b40f24e1a4dcd18185d601dc30c964c3e25112bffc1d984679059d61508a38fe

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - python >=3.8
    - apache-sedona
    - bokeh
    - cartopy
    - cenpy
    - contextily
    - cubo
    - dask-geopandas
    - datashader
    - earthengine-api
    - earthpy
    - easystac
    - eemont
    - eomaps
    - eoreader
    - fiona >=1.9.0
    - folium 
    - geemap >=0.30.4
    - geoalchemy2
    - geocube
    - geopandas
    - geotiff
    - geosnap
    - geoviews
    - h3
    - h3-py
    - hvplot
    - ipygany
    - ipyleaflet 
    - ipyvtklink
    - keplergl
    - laspy
    - leafmap >=0.30.1
    - lidar
    - localtileserver
    - lonboard
    - mapboxgl
    - mapclassify
    - mapwidget
    - movingpandas
    - netcdf4
    - odc-stac
    - osmnx
    - owslib
    - panel
    - palettable
    - pillow
    - planetary-computer
    - plotly
    - proplot
    - psycopg2
    - pydeck
    - pygis
    - pyntcloud
    - pysal
    - pyshp
    - pystac-client
    - python-duckdb
    - python-mss
    - pyvista
    - radiant-mlhub
    - rasterio
    - rasterstats
    - rio-cogeo
    - rioxarray
    - s2cloudless
    - sarpy
    - satpy
    - sentinelsat
    - shapely
    - simplekml
    - sliderule
    - spyndex
    - sqlalchemy
    - stackstac
    - tropycal
    - usgs
    - whitebox
    - whiteboxgui
    - wxee
    - xarray
    - xarray-spatial
    - xee
    - xmovie
    - xyzservices

test:
  imports:
    - geospatial
  # commands:
  #   - pip check
  requires:
    - pip

about:
  home: https://github.com/giswqs/geospatial
  summary: A Python package for installing commonly used packages for geospatial analysis and data visualization with only one command.
  description: A Python package for installing commonly used packages for geospatial analysis and data visualization with only one command.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://geospatial.gishub.org
  dev_url: https://github.com/giswqs/geospatial

extra:
  recipe-maintainers:
    - giswqs
