{% set name = "geospatial" %}
{% set version = "0.11.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/geospatial-{{ version }}.tar.gz
  sha256: 734dac0f96c58a285acee425d954f27a91cb354b87624cf1fd5e8bd09758abb7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - apache-sedona
    - bokeh
    - cartopy
    - cenpy
    - contextily
    - cubo
    - dask-ee
    - dask-geopandas
    - datashader
    - earthaccess
    - earthengine-api
    - earthpy
    - easystac
    - eemont
    - eomaps
    - eoreader
    - fiona
    - folium >=0.12.1
    - geemap >=0.34.3
    - geoalchemy2
    - geocube
    - geofileops
    - geopandas >=0.10.2
    - geotiff
    - geosnap
    - geoviews
    - h3
    - h3-py
    - hvplot
    - hypercoast
    - ipygany
    - ipyleaflet >=0.16.0
    - keplergl
    - laspy
    - leafmap >=0.37.6
    - libgdal-arrow-parquet
    - lidar
    - localtileserver >=0.10.0
    - lonboard
    - mapboxgl
    - mapclassify
    - maplibre
    - mapwidget
    - movingpandas
    - netcdf4
    - odc-stac
    - osmnx
    - overturemaps
    - owslib
    - panel
    - palettable
    - pdal
    - pillow
    - planetary-computer
    - plotly
    - psycopg2
    - pydeck
    - pygis >=0.7.0
    - pyntcloud
    - pysal
    - pyshp
    - pystac-client
    - python-mss
    - pyvista
    - radiant-mlhub
    - rasterio
    - rasterstats
    - rio-cogeo
    - rioxarray
    - s2cloudless
    - sarpy
    - satpy
    - sentinelsat
    - shapely
    - simplekml
    - sliderule
    - spyndex
    - sqlalchemy
    - stackstac
    - tropycal
    - usgs
    - whitebox
    - whiteboxgui
    - wxee
    - xarray
    - xarray-spatial
    - xee
    - xmovie
    - xyzservices

test:
  imports:
    - geospatial
  # commands:
  #   - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/opengeos/geospatial
  summary: A Python package for installing commonly used packages for geospatial analysis and data visualization with only one command.
  description: A Python package for installing commonly used packages for geospatial analysis and data visualization with only one command.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://geospatial.gishub.org
  dev_url: https://github.com/opengeos/geospatial

extra:
  recipe-maintainers:
    - giswqs
