{% set name = "geospatial" %}
{% set version = "0.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/geospatial-{{ version }}.tar.gz
  sha256: b4b5fc7b84025be82239a7d9ca658f0744b2ac43a6223086e8d078b0fa6b977a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - bokeh
    - cartopy
    - cenpy
    - contextily
    - dask-geopandas
    - datashader
    - earthengine-api
    - earthpy
    - easystac
    - eemont
    - eomaps
    - folium >=0.12.1
    - geemap >=0.18.1
    - gemgis
    - geoalchemy2
    - geocube
    - geopandas >=0.10.2
    - geosnap
    - geoviews
    - h3
    - h3-py
    - here-map-widget-for-jupyter
    - hvplot
    - ipygany
    - ipyleaflet >=0.16.0
    - ipyvtklink
    - keplergl
    - laspy
    - leafmap >=0.14.0
    - lidar
    - localtileserver >=0.6.1
    - mapboxgl
    - movingpandas
    - netcdf4
    - odc-stac
    - osmnx
    - owslib
    - panel
    - palettable
    - pillow
    - planetary-computer
    - plotly
    - proplot
    - psycopg2
    - pydeck
    - pygis >=0.5.0
    - pysal
    - pyntcloud
    - radiant-mlhub
    - rasterio
    - rasterstats
    - rio-cogeo
    - rioxarray
    - s2cloudless
    - sarpy
    - satpy
    - sentinelsat
    - shapely
    - sliderule
    - spyndex
    - sqlalchemy
    - stackstac
    - tropycal
    - xarray-spatial
    - xmovie
    - wxee

test:
  imports:
    - geospatial
  # commands:
  #   - pip check
  requires:
    - pip

about:
  home: https://github.com/giswqs/geospatial
  summary: A Python package for installing commonly used packages for geospatial analysis and data visualization with only one command.
  description: A Python package for installing commonly used packages for geospatial analysis and data visualization with only one command.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://geospatial.gishub.org
  dev_url: https://github.com/giswqs/geospatial

extra:
  recipe-maintainers:
    - giswqs
