{% set name = "geospatial" %}
{% set version = "0.5.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/geospatial-{{ version }}.tar.gz
  sha256: c6f9725d6913668fff6011d45795fcc79b544ee9f97d36021cd7a5218bf10475

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 4

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - black-jupyter
    - bump2version
    - cartopy
    - cenpy
    - codespell
    - contextily
    - dask-geopandas
    - datashader
    - earthengine-api
    - earthpy
    - easystac
    - eemont
    - eomaps
    - geemap >=0.13.7
    - gemgis
    - geoalchemy2
    - geocube
    - geopandas
    - geoviews
    - h3
    - h3-py
    - here-map-widget-for-jupyter
    - httplib2shim
    - hvplot
    - ipygany
    - ipyleaflet
    - ipynb-py-convert
    - ipyvtklink
    - jupytext
    - keplergl
    - laspy
    - leafmap
    - localtileserver
    - mapboxgl
    - movingpandas
    - netcdf4
    - odc-stac
    - osmnx
    - owslib
    - panel
    - palettable
    - pillow <=8.4.0 # required by sentinelhub
    - planetary-computer
    - plotly
    - proplot
    - psycopg2
    - pydeck
    - python-mss
    - pyntcloud
    - pyvista
    - radiant-mlhub
    - rasterio
    - rasterstats
    - rio-cogeo
    - rioxarray
    - s2cloudless
    - sarpy
    - satpy
    - sentinelsat
    - shapely
    - sliderule
    - spyndex
    - sqlalchemy
    - stackstac
    - streamlit-folium
    - voila
    - xarray-spatial
    - xmovie
    - wxee

test:
  imports:
    - geospatial
  # commands:
  #   - pip check
  requires:
    - pip

about:
  home: https://github.com/giswqs/geospatial
  summary: A Python package for installing commonly used packages for geospatial analysis and data visualization with only one command.  
  description: A Python package for installing commonly used packages for geospatial analysis and data visualization with only one command. 
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://geospatial.gishub.org
  dev_url: https://github.com/giswqs/geospatial

extra:
  recipe-maintainers:
    - giswqs
